version: "3"

services:
  db:
    image: "mariadb:10.5"
    restart: "always"
#    volumes:
#      - ./db-data:/var/lib/mysql/data
#      - ./db-logs:/var/lib/mysql/logsql
#      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    entrypoint: "mysql -u dev -ppass12 -h 127.0.0.1 cw < db/migrations/000001_init_schema.up.sql"
    networks:
      - net1
  web:
    build: .
    image: "golang:1.6.1-alpine"
#    volumes:
#      - .:/var/www
#    command: ["go", "run", "./cmd/server/main.go"]
    entrypoint: "go run cmd/server/main.go"
    ports:
      - "8088:8080"
    depends_on:
      - db
    networks:
      - net1
volumes:
  db-data:
  db-logs:

networks:
  net1:
    driver: bridge
