name: lint

on:
  push:
    branches:
      - '*'

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - uses: actions/checkout@v3
      - name: golangci-lint
        with:
          version: v1.29